name: cityholder
services:
  bot:
    build: .
    container_name: cityholder-bot
    volumes:
      - ./sessions:/app/sessions
      - ./.env:/app/.env:ro
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    security_opt:
      - seccomp=unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
